[package]
name = "rust-item-sort"
version = "0.1.0"
edition = "2021"
description = "A tool (and cargo subcommand) to sort/reorder Rust items in an opinionated way."
authors = ["Jip J. Dekker <jip@dekker.one>"]
autobins = false

[dependencies]
# Organizer core
tree-sitter = "0.26.9"
tree-sitter-rust = "0.24.2"

# cargo-organize-fmt (cargo subcommand)
cargo_metadata = "0.23"
clap = { version = "4.5", features = ["derive"] }
clap-cargo = "0.18"

[[bin]]
name = "rust-item-sort"
path = "src/bin/rust-item-sort.rs"

[[bin]]
name = "cargo-item-sort"
path = "src/bin/cargo-item-sort.rs"

[build-dependencies]
cc = "*"
